repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        stages: [pre-commit, pre-push]
        args: ["--fix", "src/config"]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        stages: [pre-commit, pre-push]
        args: ["src/config"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        stages: [pre-commit, pre-push]
        args: ["-r", "src/config"]
